In [1]:
import numpy as np

In [3]:
a = np.array([3,4,5])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a*3)   # multiply array by 3 - Broadcasting

[ 9 12 15]


In [7]:
print(a.dtype)

int64


In [8]:
print(a.ndim)  # print the dimension - is it one dimensiaonal, two dimensionol or multi-dimensional

1


In [12]:
print(a.shape) #  The "shape" of an array is a tuple with the number of elements per axis (dimension).

(3,)


In [14]:
c = np.array(["One","two"])

In [15]:
print(c.dtype)

<U3


In [18]:
a1 = np.array([[1,2,3,4,5], [2,3,4,5,6]])

In [20]:
print(a1.ndim)
print(a1.shape)

2
(2, 5)


In [22]:
# broadcast to array - a1

b=a1 * 3
print(b)

[[ 3  6  9 12 15]
 [ 6  9 12 15 18]]


In [23]:
pwd

'/Users/yogeshsharma/github'

# NUmpy - SEt Type

In [24]:
import numpy as np

a = np.array([3,4,5],dtype = 'int8') # so that array uses less space in memory

Numpy array: Ones and Zeros

In [25]:
c1 = np.ones(4,dtype = 'int32')
print(c1)

[1 1 1 1]


In [27]:
c2 = np.ones([4,4],dtype = 'int32')
print(c2)
print(c2.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(4, 4)


In [31]:
c3=np.zeros([3,3],dtype='int8')
print(c3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Numpy : eye

In [32]:
A = np.eye(3,5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [40]:
import numpy as np
A2 =np.random.randint(16,size=(3,5))  # (Range, size tell dimension shape)
print(A2)
A3= print(A2 / 2)

[[13 12  8  7  5]
 [ 6 13  7 15  0]
 [ 0  2  4  8  8]]
[[6.5 6.  4.  3.5 2.5]
 [3.  6.5 3.5 7.5 0. ]
 [0.  1.  2.  4.  4. ]]


    To get the fixed numbers from random function use "SEED"

Numpy - Array Type change by divison ( int to float)

In [46]:
    A4 = A2.transpose()
    print(A4)
    print(A4.shape)
    print(A4[1][:]) # print all elements of row 1
    print(A4[0][1],A4[1][2]) # print index 1 of row 0 and index element 2 of row 1

[[13  6  0]
 [12 13  2]
 [ 8  7  4]
 [ 7 15  8]
 [ 5  0  8]]
(5, 3)
[12 13  2]
6 2


In [50]:
a5 = np.array([[2,3,4], [5,6,7]])
b3 = np.array([3,4,5])
c3= np.multiply(a5,b3)
print(c3)

d4 = np.dot(a5,b3) #calculate the dot product primarily used for deep learning
print(d4)

[[ 6 12 20]
 [15 24 35]]
[38 74]


In [55]:
help(np.random.seed)


Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [56]:
np.random.seed(100)

In [61]:
a = np.random.randint(100,10001,50)   #
print(a)

[ 179  450 4249 8006 5746  902 4476 9971 1440 7838 9823 5869 6330 2534
 5887 2000 5093 3313 7001 5943 9320 2983 4331 3867 4959 3508  102  989
 4813 2626 9719 3353 7506 4098 3092 4049  906 8566 2340 7196 7174 4633
 1838 4469 9841 8910 8309 7321 6312  588]


# Slice As Reference

In [68]:
import numpy as np 
a = np.array([1,2,3,4])
b = a[1:3]
a[2]=50
print(b)   
print(a)

[ 2 50]
[ 1  2 50  4]


# Numpy : Slice - Copy

In [69]:
import numpy as np 
a = np.array([1,2,3,4])
b = a[1:3].copy()
print(b)
a[2]=50
print(b)  
print(a)

[2 3]
[2 3]
[ 1  2 50  4]


# Numpy : abs value on a Numpy array

In [75]:
import numpy as np

a = np.array ([[-1,-2,-3],[-9,-8,-7]])
print(a)
print(a.dtype)
print()

abs_a = np.absolute(a)
print(abs_a)
print(abs_a.dtype)


[[-1 -2 -3]
 [-9 -8 -7]]
int64

[[1 2 3]
 [9 8 7]]
int64


In [77]:
#Numpy: Logical not on a NUmpy array

import numpy as np

a = np.array([True, True, False])
print(a.dtype)
print(a)
print()

bool
[ True  True False]



#    # NUmpy: Vectorize a function

In [80]:
import numpy as np

def fibo(n):
    if n == 1 or n ==2:
        return 1
    a,b = 1,1
    for i in range(n-2):
        a,b = b, a + b
        return b
    
vfibo = np.vectorize(fibo)
a = np.array([[1,2,3,4,5],[7,8,9,10]])

print(a)
print(a.dtype)
print()

b = vfibo(a)
print(b)

[list([1, 2, 3, 4, 5]) list([7, 8, 9, 10])]
object



TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [81]:
animal = np.array(["cow","tiger", "donkey", "lion"])
vlen = np.vectorize(len)
print(vlen(animal))

[3 5 6 4]


In [89]:
animal = np.array(["cow","tiger", "donkey", "lion"])
longer_than_five = np.vectorize(lambda x: len(x) >= 5)
longer_bool = longer_than_five(animal)
print(longer_bool)

[False  True  True False]


# Numpy Filter array

In [92]:
animal = np.array(["cow","tiger", "donkey", "lion"])
longer_than_five = np.vectorize(lambda x: len(x) >= 5)
longer_bool = longer_than_five(animal)
print(longer_bool)

# Print animal names whose lengt i equal to greater than 5
long_animal_name = animal[longer_bool]
print("These are animals with longer name:",long_animal_name)

[False  True  True False]
These are animals with longer name: ['tiger' 'donkey']


# Numpy filter matrix

In [99]:
import numpy as np
import re
import timeit

scores = np.array([[23,37,18,16,29,31],
                   [12,34,56,78,21,45],
                   [44,12,34,45,31,23]])
print(scores)

[[23 37 18 16 29 31]
 [12 34 56 78 21 45]
 [44 12 34 45 31 23]]


In [100]:
high_score_booleans = (scores > 20)
print(high_score_booleans)

[[ True  True False False  True  True]
 [False  True  True  True  True  True]
 [ True False  True  True  True  True]]


In [106]:
high_scores = scores[high_score_booleans]
print(high_scores) # display elements greater than 20


[23 37 29 31 34 56 78 21 45 44 34 45 31 23]


In [121]:
def getvalues(arr, value):
    return arr[arr > value]

In [122]:
setup = '''
def getvalues(arr, value):
    return arr[arr > value]
'''

In [123]:
%%timeit

getvalues(np.array(([10,24,45],[59,89,12])),30)

5.07 µs ± 770 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [124]:
?plt.scatter

Object `plt.scatter` not found.


In [125]:
 a= 1 + 2 * 4
print(a)

9


In [134]:
import numpy as np

a = np.array([[64392, 31655],[32579, 0],[49248, 462], [0,0]], dtype = np.uint16)


print(a)
print("Array shape is", a.shape)
print("Array dimension is", a.ndim)
print("length of each element of array in byte is ", a.itemsize)

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]
Array shape is (4, 2)
Array dimension is 2
length of each element of array in byte is  2


In [141]:
import numpy as np

sampleArray = np.array([[11,22,33],[44,55,66],[77,88,99]])

# column 3 of all rows
a=sampleArray[:,2]
print(a)

[33 66 99]


In [145]:
import numpy as np

sampleArray1 = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])

b = sampleArray1[::2,1::2] # (::2 all the rows step by 2), (1::2, all the colums from col1 and step by 2)
print(b)

[[ 6 12]
 [30 36]
 [54 60]]


In [162]:
import numpy as np

sampleArray1 = np.array([[44 ,47, 64, 67],[67 ,9 ,83, 21],[36 ,87, 70, 88],[88, 12, 58, 65],[39, 87 ,46 ,88]])
print(sampleArray1)

[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]


In [156]:
sort_by_orriginal_array = np.sort(sampleArray1, axis = 0)
print(sort_by_orriginal_array)

[[36  9 46 21]
 [39 12 58 65]
 [44 47 64 67]
 [67 87 70 88]
 [88 87 83 88]]


# Sorting Numpy Array by row 
a = a[:, a[0,:].argsort()]

In [165]:
sort_by_secondrow = sampleArray1[:,sort_by_secondrow[4,:].argsort()]
print(sort_by_secondrow)

[[67 47 44 64]
 [21  9 67 83]
 [88 87 36 70]
 [65 12 88 58]
 [88 87 39 46]]


In [170]:
# Numpy array created
a = np.array([9, 3, 1, 7, 4, 3, 6])
  
# unsorted array print
print('Original array:\n', a)
  
# Return type is None
print('Return type:', a.sort())
  
# Sorted array output
print('Original array sorted->', a)

Original array:
 [9 3 1 7 4 3 6]
Return type: None
Original array sorted-> [1 3 3 4 6 7 9]


In [176]:
import numpy as np
numPyArray = np.arange(1000000)
pythonList = list(range(100000))
# without For loop
%time numPyArray = numPyArray * numPyArray
%time pythonlist = [x*x for x in pythonList]

#with for loop
%time for _in range(10): numPyArray= numPyArray * numPyArray
%time for _in range(10): pythonList = [x*x for x in pythonList]

CPU times: user 1.21 ms, sys: 18 µs, total: 1.23 ms
Wall time: 2.68 ms
CPU times: user 6.76 ms, sys: 1.9 ms, total: 8.66 ms
Wall time: 11.8 ms


SyntaxError: invalid syntax (<unknown>, line 1)

In [3]:
import numpy as np

x = np.array([[1,3,5],[1,1,1],[0,2,4]])

y = np.average(x , axis = 1)
print(y[0])
print(y[1])
print(y[2])

3.0
1.0
2.0


In [5]:
def levenshtein(a,b):
    if not a: return len(b)
    if not b: return len(a)
    return min(levenshtein(a[1:], b[1:]) +(a[0] !=b[0]),levenshtein(a[1:],b)+1,levenshtein(a,b[1:]+1)

print(levenshtein("hello","bello"))

SyntaxError: invalid syntax (<ipython-input-5-ca31143f16bf>, line 6)

# RAW EXTRACTION IN NUMPY

In [14]:
# Array ceation
import numpy as np
x = np.array ([10,20,30,40])
x1 = np.zeros(10), np.ones(10)
x2 = np.zeros([3,3], dtype = int)
x3 = np.empty([2,3,2],dtype=int)
print(x)
print(x1)
print(x2)
print(x3)

[10 20 30 40]
(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[                   0                    0]
  [                   0                    0]
  [                   0                    0]]

 [[                   0                    0]
  [                   0  2484135899465670501]
  [-8070450532247928832 -8070450532247928832]]]


In [16]:
import numpy as np
x = np.array ([[10,20,30,40],[34,45,56,67]])
y = x*x
y1 = x + x
print(y)
print(y1)

[[ 100  400  900 1600]
 [1156 2025 3136 4489]]
[[ 20  40  60  80]
 [ 68  90 112 134]]


In [24]:
#indexing and slicing

x = np.array ([[10,20,30,40],[34,45,56,67]])
y = x[1,:2] # row 1 and first 2 columns
print(y)

y1 = x[0,::2],x[1,1:]
print(y1)

[34 45]
(array([10, 30]), array([45, 56, 67]))


In [29]:
#creating an array

import numpy as np

# Dimension - how many dimension
# shape - number of element or number of rows and columns
intlist = [10,20,30,40,50]
x = np.array(intlist)
print(x.ndim)
print(x.shape)

1
(5,)


In [30]:
np.empty((2,3,2))

array([[[ 2.35541533e-312,  2.05833592e-312],
        [ 2.22809558e-312,  2.56761491e-312],
        [ 2.48273508e-312,  2.05833592e-312]],

       [[ 2.05833592e-312,  2.29175545e-312],
        [ 2.07955588e-312,  2.14321575e-312],
        [-1.28822975e-231, -2.68679486e+154]]])

In [33]:
import numpy as np

print(np.__version__)

1.15.4


In [34]:
intlist = [10,20,30,40,50]
x = np.array(intlist)

print(x[-4:-1]) # negative slicing

[20 30 40]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) # from index 1 to 5 step by 2

[2 4]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::2]) # from index 1 to end step by 2

[2 4 6]


# slicing 2 - D arrays

In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#From the second element, slice elements from index 1 to index 4 (not included):
print(arr[1,1:4])

[7 8 9]


In [38]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#From both elements, return index 2:
print(arr[0:2, 2])

[3 8]


In [39]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY : COPY

In [16]:
import numpy as np 

x = np.array([[1,2,3],[8,9,10]])

creating copying of x
a = x.copy ()

#changing first element of the first array of X
x[0,0] = 16

print("\nArray x is:\n",x)

print("\nArray a is:\n",a)


Array x is:
 [[16  2  3]
 [ 8  9 10]]

Array a is:
 [[ 1  2  3]
 [ 8  9 10]]


# NUMPY : View

In [18]:
import numpy as np 

x = np.array([[1,2,3],[8,9,10]])

# a would be effected by changes done to array "x"
a = x.view()

x[1,1] = 37

print(x)

print(a)

[[ 1  2  3]
 [ 8 37 10]]
[[ 1  2  3]
 [ 8 37 10]]


In [19]:
import numpy as np 

x = np.array([[1,2,3],[8,9,10]])

# x would be effected by changes done to array "a"
a = x.view()

a[1,1] = 12

print(x)


print(a)



[[ 1  2  3]
 [ 8 12 10]]
[[ 1  2  3]
 [ 8 12 10]]


In [20]:
import numpy as np 

x = np.array([[1,2,3],[8,9,10]])

a = x.copy()

b = x.view()

print(a.base) # a owns the data
print(b.base) # b doesn't own the data

None
[[ 1  2  3]
 [ 8  9 10]]


# Reshape from 1-D to 2-D

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape from 1-D to 3-D

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

 # first 2 tells that there will be 2 arrays that contains 3 arrays(rows) with 2 elelments each( columns)

newarr1 = arr.reshape(2, 3,2) 
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16])

 # first 2 tells that there will be 2 arrays that contains 2 arrays(rows) with 4 elelments(columsn) each

newarr2 = arr.reshape(2, 2,4) 
print(newarr2)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15,16,17,18])

newarr3= arr.reshape(2, 3, -1)

print(newarr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


# Flattening the arrays - Converting 3 D , 2D to 1D

In [44]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr4 = arr.reshape(-1)

print(newarr4)

[1 2 3 4 5 6]


# 2.5 NumPy Array Iterating
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [48]:
#Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [52]:
#Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [47]:
#Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [53]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [54]:
# Iterate down to the scalars:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [55]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].



In [58]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


# Iterating With Different Step Size
We can use filtering and followed by iteration.

In [59]:
#Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):   
  print(x)

# explanation (arr[:, ::2]) - :, represents both the array in the inner [], 
# ::2 - represents the all elements of arrays with step 2

1
3
5
7


In [60]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[::2, :]):
  print(x)

# explanation (arr[::2, :]) - :, represents within two arrays in the inner [] step by 2 , 
# : - represents the all elements of array in the selected one

1
2
3
4


In [75]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::3]):
  print(x)

# explanation (arr[:, :]) - :, represents both the array in the inner [],  
# : - represents the all elements of arrays by step 3

1
4
5
8


In [76]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[::2, ::3]):
  print(x)
# explanation (arr[:, :]) - :, represents both the array in the inner [] step by 2,  
# : - represents the all elements of arrays by step 3

1
4


In [77]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::4]):
  print(x)
# explanation (arr[:, :]) - :, represents both the array in the inner [] ,  
# : - represents the all elements of arrays by step 4

1
5


In [86]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,[::2,::3]]):
  print(x)
# explanation (arr[:, :]) - :, represents both the array in the inner [],  
# : - represents the all elements of arrays by step 3

SyntaxError: invalid syntax (<ipython-input-86-e3c36784f99d>, line 5)

# Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [87]:
#Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [88]:
# Enumerate on following 2D array's elements:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# 3.1 NumPy Array Join
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.



In [89]:
# join two arrays
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [90]:
# join join two 2-D arrays along row (axis =1)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # axis 1 stands column

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [91]:
# join join two 2-D arrays along column (axis =0)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) # axis 1 stands row

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [92]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking along Rows

In [94]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [99]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.hstack((arr1,arr2))
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Stacking along Columns

In [96]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [100]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Stacking Along Height (depth)

In [101]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# 3.2 NumPy Array Split

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [103]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [104]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr1 = np.array_split(arr, 3)

print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [105]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.array_split(arr, 4)

print(newarr3)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [106]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.array_split(arr, 7)

print(newarr3)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [109]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.split(arr, 7)

print(newarr3)

ValueError: array split does not result in an equal division

#Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [110]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays


Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.


In [111]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [112]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [113]:
# Split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using hsplit() opposite of hstack()

In [114]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

# 3.3 NumPy Array Search

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [116]:
# Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [118]:
# Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [119]:
# Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


# Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

    The searchsorted() method is assumed to be used on sorted arrays.

In [120]:
# Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


# Search From the Right Side

In [40]:
# Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


# Multiple Values
To search for more than one value, use an array with the specified values.

In [42]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)
print(arr)

[1 2 3]
[1 3 5 7]


# 3.4 NumPy Array Sort
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [43]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [44]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [45]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


# Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [47]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [51]:
import numpy as np

arr = np.array([[[3, 2, 4], [5, 0, 1],[5,6,7]]])

print(np.sort(arr))

[[[2 3 4]
  [0 1 5]
  [5 6 7]]]


# 3.5 NumPy Array Filter
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

Example

In [52]:
# Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


# Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.



In [54]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [56]:
#Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


# Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.



In [57]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [58]:
#Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [59]:
#Create a filter array that will return only dd elements from the original array:


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 1

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[ True False  True False  True False  True]
[1 3 5 7]


# 4.1 Random Intro
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

# enerate Random Number
NumPy offers the random module to work with random numbers.

In [62]:
from numpy import random

x = np.random.randint(100)
print(x)

23


# Generate Random Float
The random module's rand() method returns a random float between 0 and 1.



In [63]:
#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.23444911452647543


# Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

Integers
The randint() method takes a size parameter where you can specify the shape of an array

In [64]:
from numpy import random

x = np.random.randint(100, size= 5)
print(x)

[18 81 99 70 22]


# Generate a 2-D array with 5 rows, each row containing 5 random integers from 0 to 100:



In [65]:
from numpy import random

x = np.random.randint(100, size= (5,5))
print(x)

[[42 86  3 28 10]
 [85 71 80 41 66]
 [39 53 41 45 93]
 [ 1 82 28 85 16]
 [66  3 54 58 18]]


# Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the value

In [66]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [67]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 3 3 3]
 [5 9 5 9 3]
 [3 7 3 5 9]]


# 4.2 Data Distribution
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

